# 数据源配置
spring:
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://124.70.195.98:3306/luo_dev?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: luo_dev
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    view:
      prefix: /templates/
      suffix: .html
mybatis:
  # mybatis日志配置
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # mybatis映射文件位置配置，即当我们需要写较复杂的sql语句时需要在resouces目录下的xxMapper.xml中进行，这个配置就是指定其位置

  mapper-locations: classpath*:mapper/*.xml

pagehelper:
  #指定数据库的方言
  helper-dialect: mysql
  #分页合理化参数，默认值为false。当该参数设置为 true 时，
  #pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。
  reasonable: true
  #支持通过 Mapper 接口参数来传递分页参数，默认值false，
  #分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页
  support-methods-arguments: true
  #为了支持startPage(Object params)方法，增加了该参数来配置参数映射，用于从对象中根据属性名取值
  params: =count=countSql

logging:
  pattern:
    console: '%X{RequestNo}-%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36}[%L] - %msg%n'
